### ISSUE TITLE
umap.transform does infinite loop if data.length < nNeighbors*4

### ISSUE THREAD

**Issue by 1wheel** [PAIR-code/umap-js#30]
```
var UMAP = require('umap-js').UMAP
var d3 = require('d3')

var steps = d3.range(70).reverse()

function rand2dArray(nrows, ncols){
  return d3.range(nrows).map(_ => d3.range(ncols).map(Math.random))
}

function testLimitedData(nrows, nNeighbors, isTransform=true){
  var umap = new UMAP({nNeighbors})
  umap.fit(rand2dArray(nrows, 5))
  if (isTransform) umap.transform(rand2dArray(1, 5))

  console.log(nrows)
}


// locks up after 60
// steps.forEach(i => testLimitedData(i, 15))

// locks up after 32
// steps.forEach(i => testLimitedData(i, 8))

// locks up after 24
// steps.forEach(i => testLimitedData(i, 6))

// locks up after 16
// steps.forEach(i => testLimitedData(i, 4))

// throws error after 11
steps.forEach(i => testLimitedData(i, 4, false))
```

**Comment by cannoneyed** [comment]
Eek! Thanks for finding!

**Comment by cannoneyed** [comment]
Pretty sure this was fixed a while ago, closing...

**Comment by 1wheel** [comment]
This still throws an error on version 1.3.1

![image](https://user-images.githubusercontent.com/1643998/72626769-430b4880-3919-11ea-9842-44aa0ec81eff.png)

https://runkit.com/1wheel/umap-bug

**Comment by cannoneyed** [comment]
Reopening! Thanks @1wheel

**Comment by cannoneyed** [comment]
Fixed with https://github.com/PAIR-code/umap-js/pull/33
